meta:
  name: fetch
  version: v0.8.1-beta1
  maintainer: Brett Bohnenkamper <kittykatt@kittykatt.co>
  arch: all
  platform: linux
  section: default
  priority: extra
  description: fetch is a BASH screenshot, system, and configuration information tool
  homepage: https://github.com/KittyKatt/fetch
  license: GPLv3
  depends:
    - bash (>=4.0)
    - awk
files:
  "/usr/local/bin/fetch":
    file: fetch.sh
    mode: "0755"
  "/usr/share/fetch/config.yaml":
    file: sample.config.conf
  "/usr/share/fetch/ascii/":
    file: ascii/*
  "/usr/share/fetch/lib/":
    file: lib/*/*