style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/KittyKatt/fetch
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - dist
        - misc
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      dist: New Distribution
      misc: Miscellanious Commits
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE