name: Formatting

on:
  push:
    branches:
      - master
    paths:
      - fetch
      - sample.config.conf
      - lib/*/*.sh
      - ascii/*.sh
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  line-checker:
    name: Line Checker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Check line count doesn't exceed 100
        run: |
          if grep '.\{102\}' fetch; then (exit 1); else (exit 0); fi
