name: Release Tests

on:
  push:

env:
  APP_NAME: 'fetch'
  MAINTAINER: 'Brett Bohnenkamper'
  DESC: 'fetch is a BASH screenshot, system, and configuration information tool.'

jobs:
  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Create Debian control file
        run: bash .github/scripts/dpkg-control.sh ${{ env.CI_REF_NAME }}
      - name: Build Debian package (.deb)
        uses: singingwolfboy/build-dpkg-buster@v1
        id: build
        with:
          args: --unsigned-source --unsigned-changes
      - name: Check output files
        run: |
          ls -la
          dpkg -c *.deb
          dpkg -I *.deb