
name: Shellcheck

on:
  push:
    branches: 
      - master
    paths:
      - fetch
      - sample.config.conf
      - lib/*/*.sh
      - ascii/*.sh
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Import Problem Matchers
      uses: lumaxis/shellcheck-problem-matchers@v1
    - name: Run ShellCheck
      run: shellcheck -S warning -a -x -f gcc fetch
