name: "Tests"
on:
  pull_request:
  push:
    #branches: [ master ]

jobs:
  #test-ubuntu:
  #  runs-on: ubuntu-20.04
  #  steps:
  #  - uses: actions/checkout@v2.3.4
  #  - name: Testing exit code on Ubuntu
  #    run: ./fetch.sh --config sample.config.conf
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Testing exit code on macOS
      run: |
        brew install bash
        /usr/local/bin/bash fetch.sh --config sample.config.conf -v
  #test-windows:
  #  runs-on: windows-2019
  #  steps:
  #  - uses: actions/checkout@v2.3.4
  #  - name: Testing exit code on Windows
  #    run: bash fetch.sh --config sample.config.conf