name: "Trunk (Linting and Formatting)"
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
      - workflows
  workflow_dispatch:

jobs:
  trunk-checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.1
